#!/system/bin/sh

### INSMOD ZRAM-MODULE ON BOOT
if busybox [ -f /system/lib/modules/zram.ko ]; then
    if busybox [ -z "`busybox lsmod | busybox grep zram`" ]; then
        busybox insmod /system/lib/modules/zram.ko;
    fi;
    busybox modprobe zram zram_num_devices=2;
fi; sleep 2

### GET TOTAL AMOUNT OF
### PHYSICAL MEMORY
mem_total_kb=$(grep MemTotal /proc/meminfo | grep -E --only-matching '[[:digit:]]+')

### ASSIGN 50% OF SYSTEM MEMORY
mem_total_kb=$((mem_total_kb * 1024 / 2))

### CREATE ZRAM0
if busybox [ "`busybox grep zram0 /proc/swaps`" != "" ]; then
            busybox swapoff /dev/block/zram0;
        fi;

busybox echo 1 > /sys/block/zram0/reset;
if [ ! -f /sys/block/zram0/comp_algorithm ]; then
          echo "Warning: cannot use LZ4 compression, defaulting to LZO (slower!)"
        else
          echo -n lz4 > /sys/block/zram0/comp_algorithm;
        fi; sleep 1
busybox echo $((mem_total_kb / 2)) > /sys/block/zram0/disksize;
busybox mkswap /dev/block/zram0;
busybox swapon -p 32767 /dev/block/zram0;

### CREATE ZRAM1
if busybox [ "`busybox grep zram1 /proc/swaps`" != "" ]; then
            busybox swapoff /dev/block/zram1;
        fi;

busybox echo 1 > /sys/block/zram1/reset;
if [ ! -f /sys/block/zram1/comp_algorithm ]; then
          echo "Warning: cannot use LZ4 compression, defaulting to LZO (slower!)"
        else
          echo -n lz4 > /sys/block/zram1/comp_algorithm;
        fi; sleep 1
busybox echo $((mem_total_kb / 2)) > /sys/block/zram1/disksize;
busybox mkswap /dev/block/zram1;
busybox swapon -p 32767 /dev/block/zram1;

exit
